### ISSUE TITLE
Does not work with the recent API changes in immich

### ISSUE THREAD

**Issue by tenfire** [pman07/Immich_Notify#5]
Does not seem to work anymore after upgrading to https://github.com/immich-app/immich/releases/tag/v1.106.1

**Comment by pman07** [comment]
Yeah, looks like they changed it from "album" to "albums" ... neat. I'll get that fixed soon.

**Comment by pman07** [comment]
Ok, should be fixed. Please let me know if you have any issues, thanks!

**Comment by tenfire** [comment]
Thank you for the quick response/change. I'm sorry for not being able to test until now. Unfortunately, I get this error when I press `Get Shared Albums` on the latest docker image _(a7c66d2cbb82)_

```
[2024-07-05 04:56:46,346] ERROR in app: Exception on /getAlbums [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "//flask_app.py", line 201, in load_albums
    temp = get_albums(config, saved_albums)
  File "//flask_app.py", line 103, in get_albums
    tmp['id'] = album['id']
TypeError: string indices must be integers
10.244.0.58 - - [05/Jul/2024 04:56:46] "POST /getAlbums HTTP/1.1" 500 -
```

**Comment by pman07** [comment]
@tenfire that's certainly not ideal. I just tried deleting all my config and data files to see if I can replicate this issue. Unfortunately I can't, can you share some more details about your setup? docker compose, env variables, etc?

**Comment by tenfire** [comment]
@pman07
The cause was all on my end. My immich postgres instance was down causing immich to not function, I should have at least checked that immich was up and running before posting here, sorry.
It is all working now! 😄
Thank you for the fix

**Comment by pman07** [comment]
Phew, glad it's working for you 😀
